version: '3.9'

services:
  grpcbackend:
    build: ./grpcbackend
    ports:
      - 8081:50051
      
  grpcclient:
    build: ./grpcclient
    ports:
      - 8082:80
    environment:
      GRPC_ENDPOINT: ${GRPC_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      OTEL_SERVICE_NAME: localgrpcclient


  # grpcapimgateway:
  #   image: mcr.microsoft.com/azure-api-management/gateway:v2
  #   ports:
  #     - 8080:8080
  #   environment:
  #     config.service.endpoint: ${CONFIG_SERVICE_ENDPOINT}
  #     config.service.auth: ${CONFIG_SERVICE_AUTH}
  #     runtime.deployment.artifact.source: Azure Portal
  #     runtime.deployment.mechanism: Docker