apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbackend
  namespace: grpc
  labels:
    app: grpcbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbackend
  template:
    metadata:
      labels:
        app: grpcbackend
    spec:
      containers:
      - name: grpcbackend
        image: ghcr.io/implodingduck/apim-grpc-aca-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
       
---
apiVersion: v1
kind: Service
metadata:
  name: grpcbackend
  namespace: grpc
  labels:
    app: grpcbackend
spec:
  type: LoadBalancer
  ports:
  - port: 50050
    targetPort: 50051
    protocol: TCP
  selector:
    app: grpcbackend